version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-server-goProject
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5433:5432'
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true

  web:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    security_opt:
      - no-new-privileges:true

  go-app:
    restart: always
    build:
      context: ./bebeziansback
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    security_opt:
      - no-new-privileges:true
  
  node-app:
    restart: always
    build:
      context: ./bebeziansfront
    ports:
      - "3000:3000" 
    depends_on:
      - go-app
    security_opt:
      - no-new-privileges:true
  
  suricata:
    image: jasonish/suricata
    restart: always
    network_mode: "host"
    volumes:
      - ./suricata/rules:/var/lib/suricata/rules
      - ./suricata/log:/var/log/suricata
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
    security_opt:
      - no-new-privileges:true
    cap_add:
      - sys_nice
      - net_admin
    command: ["suricata", "-c", "/etc/suricata/suricata.yaml", "-i", "eth0"]

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=lampa1128
      - ES_JAVA_OPTS=-Xms1g -Xmx1g 
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic               
      - ELASTICSEARCH_PASSWORD=lampa1128             
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local